### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Toutouwai** [BitPoet/DatetimeAdvanced#1]
On [this line](https://github.com/BitPoet/DatetimeAdvanced/blob/eaa33613c5f4adcfc1016c46d46c7a8560d5f45b/FieldtypeDatetimeAdvanced.module#L232), `WireExpection` should be `WireException`.

**Comment by BitPoet** [comment]
Thanks for the reminder, I already eliminated that in the last changes I made but didn't commit those yet. I have now committed version 1.0.0.

**Comment by Toutouwai** [comment]
Thanks. I found another little problem but will open a separate issue for that.
