### ISSUE TITLE
Returns a string

### ISSUE THREAD

**Issue by arnasziedavicius** [BitPoet/DatetimeAdvanced#4]
Great idea for a module!

It seems to just return a string instead of object tho. I've followed the installation instructions but when used, it's not different from Datetime field.

Would you know where to look for clues to fix this? Or is there a step I've missed?

**Comment by BitPoet** [comment]
Do you get an object instead of a string if you use $page->getUnformatted("name_of_your_field") instead of directly accessing $page->name_of_your_field?

**Comment by arnasziedavicius** [comment]
Yes indeed, I eventually noticed that when using getUnformatted method it then returns an object.

Perhaps this could be mentioned in the docs?
